[versions]
agp = "8.8.2"
kotlin = "2.1.0"
coroutines = "1.9.0"
parcelize = "2.0.0-RC1"
ksp = "2.1.0-1.0.29"
coreKtx = "1.12.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
material = "1.11.0"
recyclerview = "1.3.2"
navigation = "2.7.7"
koin = "3.6.0-wasm-alpha2"
retrofit = "2.10.0"
moshi = "1.15.1"
okhttp = "4.12.0"
lifecycle = "2.7.0"
coil = "2.6.0"
mockito = "5.11.0"
turbine = "1.1.0"
appcompat = "1.6.1"
activity = "1.8.0"
constraintlayout = "2.1.4"
gms = "19.3.0"
shimmer = "0.5.0"
colorPicket = "2.3.0"
expandableLayout = "2.9.2"
numberPicker = "1.0.3"
datadogPlugin = "1.14.0"
datadog = "2.11.0"
sentry = "8.17.0"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
play-services-wallet = { group = "com.google.android.gms", name = "play-services-wallet", version.ref = "gms" }

kotlin-coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "coroutines" }

koin = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
moshi = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
moshi-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
moshi-adapters = { group = "com.squareup.moshi", name = "moshi-adapters", version.ref = "moshi" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }

shimmer = { group = "com.facebook.shimmer", name = "shimmer", version.ref = "shimmer" }
datadog-rum = { group = "com.datadoghq", name = "dd-sdk-android-rum", version.ref = "datadog" }
datadog-session-replay = { group = "com.datadoghq", name = "dd-sdk-android-session-replay-material", version.ref = "datadog" }

colorpickerview = { group = "com.github.skydoves", name = "colorpickerview", version.ref = "colorPicket" }
expandablelayout = { group = "com.github.cachapa", name = "ExpandableLayout", version.ref = "expandableLayout" }
numberpicker = { group = "com.github.ch-muhammad-adil", name = "MaterialPickerDialog", version.ref = "numberPicker" }
sentry = { group = "io.sentry", name = "sentry-android", version.ref = "sentry" }

#Test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
koin-test = { group = "io.insert-koin", name = "koin-test", version.ref = "koin" }
okhttp-mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
kotlin-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
datadog = { id = "com.datadoghq.dd-sdk-android-gradle-plugin", version.ref = "datadogPlugin" }

